image: google/cloud-sdk:latest

stages:
  - checkout
  - build
  - deploy

variables:
  PROJECT_ID: "striking-gadget-478715-b0"
  REGION: "us-central1"
  ZONE: "us-central1-a"
  REPO: "llmops-repo"
  REGISTRY: "us-central1-docker.pkg.dev"
  CLUSTER: "llmops"


checkout_code:
  stage: checkout
  script:
    - echo "Code Checked out.."

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache python3 py3-pip curl bash
    - curl -sSL https://sdk.cloud.google.com | bash
    - export PATH=$PATH:/root/google-cloud-sdk/bin
    - echo "$GCP_SA_KEY" | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud auth configure-docker $REGISTRY
  script:
    - docker build -t $REGISTRY/$PROJECT_ID/$REPO/llmops-app:latest .
    - docker push $REGISTRY/$PROJECT_ID/$REPO/llmops-app:latest

deploy_to_gke:
  stage: deploy
  before_script:
    - echo "$GCP_SA_KEY" | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud auth configure-docker $REGISTRY
  script:
    - gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $PROJECT_ID
    - kubectl apply -f kubernetes-deployment.yaml
